type Props = {
  trend: {
    reason?: string | null;
    startup_idea?: string | null;
    risks?: string | null;
    market_analysis?: string | null;
  };
};

export default function InsightCards({ trend }: Props) {
  const cards = [
    {
      icon: "💡",
      title: "Key Insight",
      content:
        trend.reason ??
        "AI will generate a key insight after the premium analysis is completed.",
    },
    {
      icon: "🚀",
      title: "Biggest Opportunity",
      content:
        trend.startup_idea ??
        "Generate a startup idea to discover the biggest opportunity.",
    },
    {
      icon: "⚠️",
      title: "Biggest Risk",
      content:
        trend.risks ??
        "Potential risks will appear after AI analysis.",
    },
    {
      icon: "🏆",
      title: "First-Mover Advantage",
      content:
        trend.market_analysis ??
        "Market advantage insights will be generated by Spoteroo AI.",
    },
  ];

  return (
    <section className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-10">
      {cards.map((card) => (
        <article
          key={card.title}
          className="glass rounded-3xl p-7 border border-white/5 hover:border-blue-500/30 transition-all duration-300"
        >
          <div className="flex items-center gap-3 mb-5">
            <div className="h-12 w-12 rounded-2xl bg-blue-500/10 flex items-center justify-center text-2xl">
              {card.icon}
            </div>

            <h3 className="text-xl font-bold">
              {card.title}
            </h3>
          </div>

          <p className="text-slate-300 leading-7 whitespace-pre-wrap">
            {card.content}
          </p>
        </article>
      ))}
    </section>
  );
}